title = "API Package"
gitRepoUrl = "https://github.com/clanny/packageAPI"

gitSourceBranch = "master"
changelog = true
classOrder = []

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"

# From git:
organizationName = "AuthorName"
projectName = "MyProjectName"
url = "https://clanny.github.io"
baseUrl = "/MyProjectName"
tagline = "Your project's tagline"

[footer]
style = "dark"
copyright = "Copyright © 2021 AuthorName. Built with Moonwave and Docusaurus"

[[footer.links]]
title = "examples"

[[footer.links.items]]
label = "example"
href = "https://example.com/"

