[package]
name = "minecraft2fun/clanny"
description = "Clanny Systems API"
version = "1.0.0"
license = "MIT"
authors = ["minecraft2fun"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"

[dependencies]